### ISSUE TITLE
Nuevas opciones

### ISSUE THREAD

**Issue by alvaroveliz** [chulini/lucho-jarascript#11]
Amigo, me gusta su plugin y lo usé con Konami Code para mi sitio; pero creo que le hace falta la opción de que no se active automáticamente para poder ejecutarlo a criterio.

SL2

**Comment by Aterbonus** [comment]
En un principio lo había pensado así, pero se opto por la [facilidad de instalación](https://github.com/chulini/lucho-jarascript/pull/8#issuecomment-169661265). 

Quizás podríamos agregar un flag al script que indique que no se desea iniciar el script de forma automática. De esta forma mantenemos la facilidad de instalación y damos la posibilidad de customizar aún más la experiencia.

Saludos.

P.D.: Podrías poner el link de tu sitio, me dió curiosidad :3

**Comment by alvaroveliz** [comment]
Eso de "Quizás podríamos agregar un flag al script que indique que no se desea iniciar el script de forma automática" me gustó, porque le indiqué un target inexistente para que no se instanciara.

Este es el sitio: http://alvaroveliz.cl

Gracias!

**Comment by chulini** [comment]
Yo estoy de viaje y no estoy en ningún computador cerca de aquí a 3 semanas
más. Si quieres implementa el flag, lo subes y yo lo apruebo desde mi cel.

On Tuesday, 7 June 2016, Alvaro Véliz notifications@github.com wrote:

> Eso de "Quizás podríamos agregar un flag al script que indique que no se
> desea iniciar el script de forma automática" me gustó, porque le indiqué un
> target inexistente para que no se instanciara.
> 
> Este es el sitio: http://alvaroveliz.cl
> 
> Gracias!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/chulini/lucho-jarascript/issues/11#issuecomment-224133559,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABVKDtJmnDboPESEkIKzjRNXU19oLm9wks5qJMM7gaJpZM4IvTfh
> .

## 

JQ | http://chulini.info

**Comment by alvaroveliz** [comment]
@chulini ya, bacán. Lo agrego y mando el pull.
